var Utils = require('./utils');

var edgeStarters = [
    "\\*teleports behind you\\*",
    "\\*teleports behind you and draws a katana\\*",
    "\\*draws katana\\*",
    "\\*draws a black katana\\*",
    "\\*leans against wall\\*",
    "\\*looks at you as if you were nothing\\*",
    "\\*teleports behind you\\* **psch...**",
    "\\*laughs maniatically\\*",
    "\\*smiles sadistically, eyes wide\\*",
    "\\*smirks\\*",
    "\\*covers itself with a cape\\*",
    "\\*kills you\\*",
    "\\*stops time\\*",
    "\\*reaches its final form\\*",
    "\\*moves so fast that you can't see it comming\\*",
    "\\*charges up power\\*",
    "\\*disappears but you hear a whisper\\*",
    "\\*its power level suddenly increases\\*",
    "\\*is surrounded by a dark aura\\*",
    "\\*its hair turns white and its eyes glow red\\*",
    "\\*smiles grimly\\*",
    "\\*dissapears in the shadows\\*",
    "\\*whispers from behind you\\*",
    "\\*irradiates a powerful dark aura\\*",
    "\\*extends its devil wings and flies over you\\*",
    "\\*extends an angel wing and a devil wing\\*",
    "\\*extends black angel wings and flies over you\\*",
    "\\*covers its face with a dark hood\\*",
    "\\*gazes at you from over its shoulder\\*",
    "\\*kills you three times before you hit the ground\\*",
    "\\*its eyes glow red\\*",
    "\\*licks blood from its knife\\*",
    "\\*leans against wall\\*",
    "\\*scoffs\\*",
    "\\*powers up\\*",
    "\\*smirks with disdain\\*",
    "\\*stares at you from the corner of the room\\*",
    "\\*looks into your eyes as your life fades away\\*",
    "\\*kills you, but you still haven't noticed\\*",
    "\\*turns into its half-demon form\\*",
    "\\*wields the power of good and evil\\*",
    "\\*is mysterious yet friendly\\*",
    "\\*was abandoned as a child\\*",
    "\\*you can feel death approaching\\*",
    "\\*kills your family\\*",
    "\\*finishes you off\\*",
    "\\*has an eye of each colour\\*",
    "\\*irradiates a cold hearted aura but you feel that you can be friends with it\\*",
    "\\*is neither good nor evil\\*",
    "\\*is beyond silly concepts such as good and evil\\*",
    "\\*wields a cursed sword\\*",
    "\\*has a scar on its face but is beautiful\\*",
    "\\*original character do not steal\\*",
    "\\*is very smart\\*",
    "\\*runs at you intelligently\\*",
    "\\*is better than you in every way\\*",
    "\\*is an all-powerful god of death\\*",
    "\\*sighs, knowing your unavoidable fate\\*",
    "\\*silently judges you\\*",
    "\\*silently judges your futile attempts\\*",
    "\\*sighs\\*",
    "\\*crosses its arms\\*",
    "\\*lifts its blindbold\\*",
    "\\*lifts its blindbold. its eyes pierces through your soul\\*",
    "\\*its eyes pierces through your soul\\*",
    "\\*The agonising pain of a thousand souls brights briefly in its eyes\\*",
    "\\*is colder than steel and ice\\*",
    "\\*is the two sides of a coin\\*",
    "\\*is fire and ice at the same time\\*",
    "\\*is burdened by a tragic past\\*",
    "\\*is a mere husk from its former self\\*",
    "\\*only lives for hatred\\*",
    "\\*transforms into its dragon form\\*",
    "\\*is half-dragon\\*",
    "\\*has dragon blood\\*",
    "\\*is half-demon\\*",
    "\\*has demon-blood\\*",
    "\\*you feel fear\\*",
    "\\*is an all powerful god of sex\\*",
    "\\*its sole presence inspires fear\\*",
    "\\*takes away its blindfold, showing its draconid eyes\\*",
    "\\*has one red eye and one dragon eye\\*",
    "\\*has dragon eyes\\*",
    "\\*is very scary but very attractive too\\*",
    "\\*has dark scales through its body\\*",
    "\\*kills you in a smart way\\*",
    "\\*solves the situation intelligently\\*",
    "\\*oc do not steel\\*",
    "\\*destroys everything you hold dear\\*",
    "\\*is an orphan\\*",
    "\\*doesn't know the meaning of love\\*",
    "\\*has a sad and tragic backstory\\*",
    "\\*is a shadow that cannot be seen\\*",
    "\\*is immortal\\*",
    "\\*is immortal and that's very tragic\\*",
    "\\*looks deadly\\*"
];

var edgePhrases = [
    "I am death. You are merely still living.",
    "Death was my begining: It will be your end.",
    "You're already dead.",
    "Misery is my nourishment... And I feel hungry.",
    "Pain? You don't know pain. Luckily for you, I'm an excellent teacher.",
    "Time waits for no one... And yours is up.",
    "You're but another scratch on my blade.",
    "I'm the nightmare you can't wake up from.",
    "Do you know what lurks in the shadows? Too bad...",
    "That sound? It was your life comming to an end.",
    "I will make you fade away.",
    "I am a wolf. You're merely a sheep.",
    "I may be dead inside, but you will be dead all over.",
    "My soul may be black, but yours will never shine again.",
    "Life is only an illussion. Let me help you wake up.",
    "I'm what gazes back from the abyss.",
    "Were you even alive in the first place?",
    "Nothin personnel... Kid.",
    "We have a name for your kind: Prey.",
    "Your life I can end, but the monsters within myself cannot be defeated.",
    "My parents are dead. So will you.",
    "This isn't even my final form.",
    "You're just an insect that needs to be squashed.",
    "Not afraid? Fool... I will make you tremble.",
    "I've walked dark paths you couldn't even dare to imagine.",
    "Give me a taste of your soul.",
    "This world will perish... But you won't be here to see it.",
    "Your will is no longer your own.",
    "I am the monster that haunts your nightmares.",
    "Madness wil consume you.",
    "You are not prepared to face me.",
    "Everyone has a dark side... I just happen to have lost my light.",
    "I am the reaper.",
    "Don't blame me, blame the society that made me.",
    "My thoughts destroyed me more than my blades will destroy you.",
    "Life is a disease and I'm here to cure it.",
    "Pathetic.",
    "I will show you the true meaning of suffering.",
    "In this world there is fear, death, evil... And me.",
    "Sore throat? I have the perfect cure: A blade.",
    "I am not the hero the world wants but the villain it deserves.",
    "Your tears are all the payment I will ever need.",
    "Life is a prision. Let me set you free.",
    "Check mate.",
    "Nobody can save you from me.",
    "Die! Die! Die!",
    "The only moment I feel truly alive is when I kill.",
    "Your life is worthless to me. But I will still take it away from you.",
    "Let me feed on your suffering.",
    "Death comes to us all... I'll make sure yours arrives soon.",
    "Your life is mine.",
    "You cannot escape.",
    "Your end will make my day.",
    "Can you hear your death approaching?",
    "I am a creature of the night.",
    "My power is beyond your comprehension.",
    "Face my wrath!",
    "I will make you wish you had never been born.",
    "I killed many before and will kill many more: Your death is not special to me.",
    "Die.",
    "Omae wa mou... Shindeiru.",
    "You are not worth my effort.",
    "You will never understand how I feel.",
    "I hurt those I love but I destroy those I hate.",
    "My cold heart has no room for mercy.",
    "Those around me always get hurt... Guess where I am now.",
    "There is no hope for someone like me.",
    "My blade hungers.",
    "I was born from hate, you will born by it.",
    "My blade is as sharp as my hate for those still living.",
    "There is no hope.",
    "You are weak.",
    "Foolish.",
    "In the end, you died alone.",
    "There is no escape. Not in this life, not in the next.",
    "I will hunt you down.",
    "I am a hunter; you are my pray.",
    "I will set your soul free of the pain of living.",
    "My power level is superior to yours.",
    "Give up. It is too late for you.",
    "My hatred is unending. Yours will perish now.",
    "You were hardly a challenge.",
    "Do not approach me, mongrel.",
    "I will destroy everything you hold dear.",
    "I will right the wrongs of your puny kind.",
    "Life is an overrated phenomenon.",
    "Why should I care?",
    "What is done cannot be undone.",
    "There is no turning back now.",
    "You activated my trap card.",
    "Hate you, me? Do you hate the ants you step on?",
    "Chaos for the fly is routine for the spider.",
    "Why should I care for those I kill? Do you care for the bread you eat?"
];

function edge() {
    return Utils.GetRandomFromList(edgeStarters)
        + " ***" + Utils.GetRandomFromList(edgePhrases) + "***";
}

module.exports = {
    'Edge' : edge
};