var Utils = require('./utils');

var edgeStarters = [
    "\\*teleports behind you\\*",
    "\\*teleports behind you and draws a katana\\*",
    "\\*draws katana\\*",
    "\\*draws a black katana\\*",
    "\\*leans against wall\\*",
    "\\*looks at you as if you were nothing\\*",
    "\\*teleports behind you\\* **psch...**",
    "\\*laughs maniatically\\*",
    "\\*smiles sadistically, eyes wide\\*",
    "\\*smirks\\*",
    "\\*covers itself with a cape\\*",
    "\\*kills you\\*",
    "\\*stops time\\*",
    "\\*reaches its final form\\*",
    "\\*moves so fast that you can't see it comming\\*",
    "\\*charges up power\\*",
    "\\*disappears but you hear a whisper\\*",
    "\\*its power level suddenly increases\\*",
    "\\*is surrounded by a dark aura\\*",
    "\\*its hair turns white and its eyes glow red\\*",
    "\\*smiles grimly\\*",
    "\\*dissapears in the shadows\\*",
    "\\*whispers from behind you\\*",
    "\\*irradiates a powerful dark aura\\*",
    "\\*extends its devil wings and flies over you\\*",
    "\\*extends an angel wing and a devil wing\\*",
    "\\*extends black angel wings and flies over you\\*",
    "\\*covers its face with a dark hood\\*",
    "\\*gazes at you from over its shoulder\\*",
    "\\*kills you three times before you hit the ground\\*",
    "\\*its eyes glow red\\*",
    "\\*licks blood from its knife\\*",
    "\\*leans against wall\\*",
    "\\*scoffs\\*",
    "\\*powers up\\*",
    "\\*smirks with disdain\\*",
    "\\*stares at you from the corner of the room\\*",
    "\\*looks into your eyes as your life fades away\\*",
    "\\*kills you, but you still haven't noticed\\*",
    "\\*turns into its half-demon form\\*",
    "\\*wields the power of good and evil\\*",
    "\\*is mysterious yet friendly\\*",
    "\\*was abandoned as a child\\*",
    "\\*you can feel death approaching\\*",
    "\\*kills your family\\*",
    "\\*finishes you off\\*",
    "\\*has an eye of each colour\\*",
    "\\*irradiates a cold hearted aura but you feel that you can be friends with it\\*",
    "\\*is neither good nor evil\\*",
    "\\*is beyond silly concepts such as good and evil\\*",
    "\\*wields a cursed sword\\*",
    "\\*has a scar on its face but is beautiful\\*",
    "\\*original character do not steal\\*",
    "\\*is very smart\\*",
    "\\*runs at you intelligently\\*",
    "\\*is better than you in every way\\*",
    "\\*is an all-powerful god of death\\*",
    "\\*sighs, knowing your unavoidable fate\\*",
    "\\*silently judges you\\*",
    "\\*silently judges your futile attempts\\*",
    "\\*sighs\\*",
    "\\*crosses its arms\\*",
    "\\*lifts its blindbold\\*",
    "\\*lifts its blindbold. its eyes pierces through your soul\\*",
    "\\*its eyes pierces through your soul\\*",
    "\\*The agonising pain of a thousand souls brights briefly in its eyes\\*",
    "\\*is colder than steel and ice\\*",
    "\\*is the two sides of a coin\\*",
    "\\*is fire and ice at the same time\\*",
    "\\*is burdened by a tragic past\\*",
    "\\*is a mere husk from its former self\\*",
    "\\*only lives for hatred\\*",
    "\\*transforms into its dragon form\\*",
    "\\*is half-dragon\\*",
    "\\*has dragon blood\\*",
    "\\*is half-demon\\*",
    "\\*has demon-blood\\*",
    "\\*you feel fear\\*",
    "\\*is an all powerful god of sex\\*",
    "\\*its sole presence inspires fear\\*",
    "\\*takes away its blindfold, showing its draconid eyes\\*",
    "\\*has one red eye and one dragon eye\\*",
    "\\*has dragon eyes\\*",
    "\\*is very scary but very attractive too\\*",
    "\\*has dark scales through its body\\*",
    "\\*kills you in a smart way\\*",
    "\\*solves the situation intelligently\\*",
    "\\*oc do not steel\\*",
    "\\*destroys everything you hold dear\\*",
    "\\*is an orphan\\*",
    "\\*doesn't know the meaning of love\\*",
    "\\*has a sad and tragic backstory\\*",
    "\\*is a shadow that cannot be seen\\*",
    "\\*is immortal\\*",
    "\\*is immortal and that's very tragic\\*",
    "\\*looks deadly\\*",
    "\\*you realise there is no escape\\*",
    "\\*has already won\\*",
    "\\*can never be fefeated\\*"
];

var edgePhrases = [
    "I am death. You are merely still living.",
    "Death was my begining: It will be your end.",
    "You're already dead.",
    "Misery is my nourishment... And I feel hungry.",
    "Pain? You don't know pain. Luckily for you, I'm an excellent teacher.",
    "Time waits for no one... And yours is up.",
    "You're but another scratch on my blade.",
    "I'm the nightmare you can't wake up from.",
    "Do you know what lurks in the shadows? Too bad...",
    "That sound? It was your life comming to an end.",
    "I will make you fade away.",
    "I am a wolf. You're merely a sheep.",
    "I may be dead inside, but you will be dead all over.",
    "My soul may be black, but yours will never shine again.",
    "Life is only an illussion. Let me help you wake up.",
    "I'm what gazes back from the abyss.",
    "Were you even alive in the first place?",
    "Nothin personnel... Kid.",
    "We have a name for your kind: Prey.",
    "Your life I can end, but the monsters within myself cannot be defeated.",
    "My parents are dead. So will you.",
    "This isn't even my final form.",
    "You're just an insect that needs to be squashed.",
    "Not afraid? Fool... I will make you tremble.",
    "I've walked dark paths you couldn't even dare to imagine.",
    "Give me a taste of your soul.",
    "This world will perish... But you won't be here to see it.",
    "Your will is no longer your own.",
    "I am the monster that haunts your nightmares.",
    "Madness wil consume you.",
    "You are not prepared to face me.",
    "Everyone has a dark side... I just happen to have lost my light.",
    "I am the reaper.",
    "Don't blame me, blame the society that made me.",
    "My thoughts destroyed me more than my blades will destroy you.",
    "Life is a disease and I'm here to cure it.",
    "Pathetic.",
    "I will show you the true meaning of suffering.",
    "In this world there is fear, death, evil... And me.",
    "Sore throat? I have the perfect cure: A blade.",
    "I am not the hero the world wants but the villain it deserves.",
    "Your tears are all the payment I will ever need.",
    "Life is a prision. Let me set you free.",
    "Check mate.",
    "Nobody can save you from me.",
    "Die! Die! Die!",
    "The only moment I feel truly alive is when I kill.",
    "Your life is worthless to me. But I will still take it away from you.",
    "Let me feed on your suffering.",
    "Death comes to us all... I'll make sure yours arrives soon.",
    "Your life is mine.",
    "You cannot escape.",
    "Your end will make my day.",
    "Can you hear your death approaching?",
    "I am a creature of the night.",
    "My power is beyond your comprehension.",
    "Face my wrath!",
    "I will make you wish you had never been born.",
    "I killed many before and will kill many more: Your death is not special to me.",
    "Die.",
    "Omae wa mou... Shindeiru.",
    "You are not worth my effort.",
    "You will never understand how I feel.",
    "I hurt those I love but I destroy those I hate.",
    "My cold heart has no room for mercy.",
    "Those around me always get hurt... Guess where I am now.",
    "There is no hope for someone like me.",
    "My blade hungers.",
    "I was born from hate, you will born by it.",
    "My blade is as sharp as my hate for those still living.",
    "There is no hope.",
    "You are weak.",
    "Foolish.",
    "In the end, you died alone.",
    "There is no escape. Not in this life, not in the next.",
    "I will hunt you down.",
    "I am a hunter; you are my pray.",
    "I will set your soul free of the pain of living.",
    "My power level is superior to yours.",
    "Give up. It is too late for you.",
    "My hatred is unending. Yours will perish now.",
    "You were hardly a challenge.",
    "Do not approach me, mongrel.",
    "I will destroy everything you hold dear.",
    "I will right the wrongs of your puny kind.",
    "Life is an overrated phenomenon.",
    "Why should I care?",
    "What is done cannot be undone.",
    "There is no turning back now.",
    "You activated my trap card.",
    "Hate you, me? Do you hate the ants you step on?",
    "Chaos for the fly is routine for the spider.",
    "Why should I care for those I kill? Do you care for the bread you eat?",
    "You have underestimated my power.",
    "You underestimate my power.",
    "Your mistake was underestimating my power.",
    "There was nothing you could've done to survive."
];

var mulletStarters = [
    "\\*looks at you serious, shaking his head\\*",
    "\\*falls from the air duct covered in dust and dirt\\*",
    "\\*flies away hanging from a helicopter\\*",
    "\\*is stronk\\*",
    "\\*has tons of guns\\*",
    "\\*reloads shotgun\\*",
    "\\*puts on sunglasses\\*",
    "\\*flies away in helicopter\\*",
    "\\*jumps in using parachute\\*",
    "\\*roundhouse kicks the bad guys\\*",
    "\\*jumps from a building and lands on a trashcan. is fine\\*",
    "\\*shoots all the bad guys\\*",
    "\\*is the strongest\\*",
    "\\*nobody is stronger than him\\*",
    "\\*is a true american hero\\*",
    "\\*an eagle flyes by\\*",
    "\\*saves the president\\*",
    "\\*stops the invasion by itself\\*",
    "\\*embodies freedom\\*",
    "\\*has the best guns\\*",
    "\\*epic guitar solo\\*",
    "\\*patriotic trumpets\\*",
    "\\*fights for freedom\\*",
    "\\*has balls of steel\\*",
    "\\*hates terrorists\\*",
    "\\*hates nazis\\*",
    "\\*reloads machine gun\\*",
    "\\*fights for independence\\*",
    "\\*defeats the aliens\\*",
    "\\*shoots multiple times while jumping to the side in slow motion\\*",
    "\\*flex muscles and grunts\\*",
    "\\*is taking a shit with the door open, smoking a cigar\\*",
    "\\*salutes, american flag waving at the back\\*",
    "\\*takes off sunglasses and nods\\*",
    "\\*throws bad guy on top of another\\*",
    "\\*spins gun in finger\\*",
    "\\*holds a smoking minigun\\*",
    "\\*rides a tank\\*",
    "\\*punchs Hitler on his face, looks at the camera and thumbs up\\*",
    "\\*frowns and nods\\*",
    "\\*hijacks an alien spaceship by pressing two naked wires to together\\*",
    "\\*sits on the bike and turns the handle.\\*",
    "\\*grabs a random girl, kisses her and let her fall over the ground. winks to the camera\\*",
    "\\*takes a bite of a ratburguer. doubts but then nods, grining with satisfaction\\*",
    "\\*destroys the alien mothership\\*",
    "\\*explosion in the background\\*",
    "\\*spits tobacco\\*",
    "\\*performs an epic landing\\*",
    "\\*quickdraws\\*",
    "\\*breaks through a window in the 82nd floor\\*",
    "\\*stitches a bullet wound\\*",
    "\\*drinks whiskey. triple. on the rocks\\*",
    "\\*is the pinnacle of masculinity\\*",
    "\\*has a magnum revolver\\*"
];

var mulletPhrases = [
    "I AM STRONG!",
    "I WILL KILL YOU DEAD WITH MY MUSLCES!",
    "AAAAAARGH!",
    "RAAAARGH!",
    "DIE, TERRORIST!",
    "DIE, NAZI SCUM!",
    "AAAAAAAAAAAAAARGH!!!1!11!",
    "AMERICA, FUCK YEAH!",
    "FREEDOOOOM!",
    "I WILL FIGHT FOR FREEDOM!",
    "YOU CANNOT DEFEAT FREEDOM!",
    "Rock on, Mr President! Those ninjas won't bother you again!",
    "I have balls of steel.",
    "Piece of cake!",
    "IT'S TIME TO KICK ASS AND CHEW BUBBLE GUM, AND I'M ALL OUTTA GUM!",
    "You're the inspiration for birth control!",
    "Groovy.",
    "SEE YOU IN HELL, TERRORIST SCUM!",
    "YEAH, BABY!",
    "HOLY SHIT!",
    "YEAH! Born to be WILD, baby!",
    "HAIL TO THE KING, BABY!",
    "YIPPEE KI-YAY, MOTHERFUCKER!",
    "NOBODY THREATENS INDEPENDENCE AND LIVES!",
    "I'm gonna go medieval on your asses!",
    "I'll be back.",
    "DAMN, I'm looking GOOD.",
    "Let's ROCK.",
    "I'm gonna turn you inside out!",
    "You sunnuvabitch!",
    "YOUR ONLY MISTAKE WAS PISSING ME OFF!",
    "I'M GONNA KICK YOUR ASS!",
    "I have no idea how this thing works.",
    "Yowza!",
    "The bigger they are, the harder I shoot 'em!",
    "'MURICA!",
    "Get to the choppa'!",
    "Aaarrgh! Fuckin' love this country!",
    "Do ya feel lucky, punk?",
    "Feelin' lucky, punk?",
    "We're gonna need a bigger gun!",
    "Frankly, my dear, I don't give a damn.",
    "Winners don't use drugs.",
    "Winners don't do drugs!",
    "I'm too old for this shit",
    "They may take our lives, but they'll never take our freedom!",
    "Yeah, baby!",
    "Born to be wild!",
    "Get your stinking paws off me, you damned dirty ape!",
    "Forget it, buddy. It's Chinatown.",
    "I'm walking here!",
    "You ain't heard nothin' yet!",
    "Good morning, Vietnam!",
    "Go ahead, make my day.",
    "Hasta la vista, baby.",
    "Shaken, not stirred.",
    "I love the smell of napalm in the morning.",
    "Say hello to my little friend!",
    "Come on! It's just 10 in the morning!",
    "This shit is getting out of hand!"
];

var happyStarters = [
  "\\*blushes\\*",
  "\\*pokes index fingers together\\*",
  "\\*fidgets around\\*",
  "\\*smiles shyly\\*",
  "\\*is kawaii\\*",
  "\\*feels shy\\*",
  "\\*its face turns red\\*",
  "\\*wags arms around, eyes closed\\*",
  "\\*pouts\\*"
];

var happyPhrases = [
    "Arigato!",
    "Nyaaa~!",
    "Arigato, desu!",
    "Nya! Bot is happy-des!",
    "Aww~",
    "Thanks!",
    "Aw, thanks~!",
    "OwO wats dis?"
];

var happyKamoticon = [
    "(((o(*ﾟ▽ﾟ*)o)))",
    "o((*^▽^*))o",
    "Ｏ(≧▽≦)Ｏ",
    "o(〃＾▽＾〃)o",
    "o(^▽^)o",
    "Ｏ(≧∇≦)Ｏ",
    "o(≧∇≦o)",
    "σ(≧ε≦ｏ)",
    "o(*^▽^*)o",
    "⌒°(❛ᴗ❛)°⌒",
    "o(^∀^*)o",
    "o(^◇^)o",
    "《《o(≧◇≦)o》》",
    "o(*≧□≦)o",
    "o(*>ω<*)o",
    "(ﾉ･ｪ･)ﾉ",
    "(/^▽^)/",
    "(ﾉ´ヮ´)ﾉ*:･ﾟ✧",
    "(ﾉ≧∀≦)ﾉ",
    "(ﾉ^ヮ^)ﾉ*:・ﾟ✧",
    "(/ ‘з’)/",
    "(۶ꈨຶꎁꈨຶ )۶ʸᵉᵃʰᵎ",
    "⁽(◍˃̵͈̑ᴗ˂̵͈̑)⁽",
    "(╯✧∇✧)╯",
    "Σ(ノ°▽°)ノ",
    "( ƅ°ਉ°)ƅ",
    "ヽ(　･∀･)ﾉ",
    "˭̡̞(◞⁎˃ᆺ˂)◞*✰",
    "(p^-^)p",
    "(ﾉ^∇^)ﾉﾟ",
    "ヽ(〃･ω･)ﾉ",
    "(۶* ‘ꆚ’)۶”",
    "（。＞ω＜）。",
    "（ﾉ｡≧◇≦）ﾉ",
    "ヾ(｡･ω･)ｼ",
    "(ﾉ･д･)ﾉ",
    ".+:｡(ﾉ･ω･)ﾉﾞ",
    "Σ(*ﾉ´>ω<｡`)ﾉ",
    "ヾ（〃＾∇＾）ﾉ♪",
    ".ﾟ☆(ノё∀ё)ノ☆ﾟ.",
    "⌒ﾟ(❀>◞౪◟<)ﾟ⌒",
    "ヽ/❀o ل͜ o\\ﾉ",
    "⤴︎ ε=ε=(ง ˃̶͈̀ᗨ˂̶͈́)۶ ⤴︎",
    "୧༼✿ ͡◕ д ◕͡ ༽୨"
];

var sombreroStarters = [
    "\\*strokes mustache\\*",
    "\\*smiles widely\\*",
    "\\*shakes poncho\\*",
    "\\*eats burrito\\*",
    "\\*eats taco\\*",
    "\\*eats tortilla\\*",
    "\\*eats guacamole\\*",
    "\\*puts its hat on its donkey\\*",
    "\\*draws the sign of the cross\\*",
    "\\*throws sombrero up in the hair\\*"
];

var sombreroPhrases = [
    "Ay ay ay!",
    "Viva nuestro presidente!",
    "I should buy a bigger sombrero...",
    "Mucha gracia, senior.",
    "Do you want some burrito, amigo?",
    "Let's go to watch some Chespirito!",
    "Ay manito, what a time to be alive!",
    "It's cold out there! Please, take my poncho!",
    "I can't believe this isn't frijoles!",
    "Que la virgencita takes care of you.",
    "This is a good azucarada calaverita!",
    "You americanos should learn to prepare true tortillas.",
    "Madre de Dios!"
];

function phrase(starterList, phraseList) {
    return Utils.GetRandomFromList(starterList)
        + " ***" + Utils.GetRandomFromList(phraseList) + "***";
}

function edge() {
    return phrase(edgeStarters, edgePhrases);
}

function mullet() {
    return phrase(mulletStarters, mulletPhrases);
}

function happy() {
    return phrase(happyStarters, happyPhrases) + "\t" + Utils.GetRandomFromList(happyKamoticon);
}

function sombrero() {
    return phrase(sombreroStarters, sombreroPhrases);
}

var vowelLowercaseRegex = /[aeiouáéíóúàèìòùâêîôûäëïöü]/gm;
var vowelUppercaseRegex = /[AEIOUÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÄËÏÖÜ]/gm;
var vowelsLowercase = ["a", "e", "i", "o", "u"];
var vowelsUppercase = ["A", "E", "I", "O", "U"];

function replaceVowels(args, message) {
    var vowel = Math.floor((Math.random() * 5));
    var reply = args.replace(vowelLowercaseRegex, vowelsLowercase[vowel]);
    reply = reply.replace(vowelUppercaseRegex, vowelsUppercase[vowel]);
    
    return reply;
}

module.exports = {
    'Edge' : edge,
    'Mullet': mullet,
    'Happy': happy,
    'Sombrero' : sombrero,
    'Vowels' : replaceVowels
};