var Utils = require('./utils');

var edgeStarters = [
    "\\*teleports behind you\\*",
    "\\*teleports behind you and draws a katana\\*",
    "\\*draws katana\\*",
    "\\*draws a black katana\\*",
    "\\*leans against wall\\*",
    "\\*looks at you as if you were nothing\\*",
    "\\*teleports behind you\\* psch...",
    "\\*laughs maniatically\\*",
    "\\*smiles sadistically, eyes wide\\*",
    "\\*smirks\\*",
    "\\*covers himself with a cape\\*",
    "\\*kills you\\*",
    "\\*stops time\\*",
    "\\*reaches its final form\\*",
    "\\*moves so fast that you can't see it comming\\*",
    "\\*charges up power\\*",
    "\\*disappears but you hear a whisper\\*",
    "\\*its power level suddenly increases\\*",
    "\\*is surrounded by a dark aura\\*",
    "\\*its hair turns white and its eyes glow red\\*",
    "\\*smiles grimly\\*",
    "\\*dissapears in the shadows\\*",
    "\\*whispers from behind you\\*",
    "\\*irradiates a powerful dark aura\\*",
    "\\*extends its devil wings and flies over you\\*",
    "\\*extends an angel wing and a devil wing\\*",
    "\\*extends black angel wings and flies over you\\*",
    "\\*covers its face with a dark hood\\*",
    "\\*gazes at you from over its shoulder\\*",
    "\\*kills you three times before you hit the ground\\*",
    "\\*its eyes glow red\\*",
    "\\*licks blood from its knife\\*",
    "\\*leans against wall\\*",
    "\\*scoffs\\*",
    "\\*powers up\\*",
    "\\*smirks with disdain\\*"
];

var edgePhrases = [
    "I am death. You are merely still living.",
    "Death was my begining: It will be your end.",
    "You're already dead.",
    "Misery is my nourishment... And I feel hungry.",
    "Pain? You don't know pain. Luckily for you, I'm an excellent teacher.",
    "Time waits for no one... And yours is up.",
    "You're but another scratch on my blade.",
    "I'm the nightmare you can't wake up from.",
    "Do you know what lurks in the shadows? Too bad...",
    "That sound? It was your life comming to an end.",
    "I will make you fade away.",
    "I am a wolf. You're merely a sheep.",
    "I may be dead inside, but you will be dead all over.",
    "My soul may be black, but yours will never shine again.",
    "Life is only an illussion. Let me help you wake up.",
    "I'm what gazes back from the abyss.",
    "Were you even alive in the first place?",
    "Nothin personnel... Kid.",
    "We have a name for your kind: Prey.",
    "Your life I can end, but the monsters within myself cannot be defeated.",
    "My parents are dead. So will you.",
    "This isn't even my final form.",
    "You're just an insect that needs to be squashed.",
    "Not afraid? Fool... I will make you tremble.",
    "I've walked dark paths you couldn't even dare to imagine.",
    "Give me a taste of your soul.",
    "This world will perish... But you won't be here to see it.",
    "Your will is no longer your own.",
    "I am the monster that haunts your nightmares.",
    "Madness wil consume you.",
    "You are not prepared to face me.",
    "Everyone has a dark side... I just happen to have lost my light.",
    "I am the reaper.",
    "Don't blame me, blame the society that made me.",
    "My thoughts destroyed me more than my blades will destroy you.",
    "Life is a disease and I'm here to cure it.",
    "Pathetic.",
    "I will show you the true meaning of suffering.",
    "In this world there is fear, death, evil... And me.",
    "Sore throat? I have the perfect cure: A blade.",
    "I am not the hero the world wants but the villain it deserves.",
    "Your tears are all the payment I will ever need.",
    "Life is a prision. Let me set you free.",
    "Check mate.",
    "Nobody can save you from me."
];

function edge() {
    return Utils.GetRandomFromList(edgeStarters)
        + " ***" + Utils.GetRandomFromList(edgePhrases) + "***";
}

module.exports = {
    'Edge' : edge
};